version: '3.8'

services:
  bot:
    container_name: codebatai_bot
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npx nodemon npm start
